#sky:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: localhost
#    port: 3306
#    database: ding-checkin
#    username: root
#    password: root123

info:
  user-account:
    - username: f2236607434
      password: fxj20060127.
      email: f2236607434@email.swu.edu.cn